export const viewListConst = {
    serversColumns: {
        columnProp : ['name', 'instances', 'ram', 'hardDisk', 'type', 'status'],
        paginationProp: [5, 10, 25]
    },
    tile : [
        {
            bgColor: 'color-bg-Blue-3',
            text: 'North East',
            icon: 'perm_data_setting',
            title: 'US East (Ohio)',
            region: 'us-east-2',
            location : 'Ohio',
            zones: '6',
            launched :'2006',
            usage: '35',
            content: {
                title: 'US East (Ohio)',
                text: 'Physical location around the world where we cluster data centers. We call each group of logical data centers an Availability Zone',
                activeServers: '2585',
                failedServers: '415',
                underMainServers: '315',
            },
        },
        {
            bgColor: 'color-bg-Lit-Tale-2',
            text: 'North East',
            icon: 'perm_data_setting',
            title: 'US West (N. California)',
            region: 'us-west-1',
            location : 'N. California',
            zones: '0',
            launched :'2006',
            usage: '80',
            content: {
                title: 'US West (N. California)',
                text: 'Physical location around the world where we cluster data centers. We call each group of logical data centers an Availability Zone',
                activeServers: '2585',
                failedServers: '415',
                underMainServers: '315',
            },
        },
        {
            bgColor: 'color-bg-DeepPurple',
            text: 'North East',
            icon: 'perm_data_setting',
            title: 'US East (N. Virginia)',
            region: 'us-east-1',
            location : 'N. Virginia',
            zones: '6',
            launched :'2006',
            usage: '45',
            content: {
                title: 'US East (N. Virginia)',
                text: 'Physical location around the world where we cluster data centers. We call each group of logical data centers an Availability Zone',
                activeServers: '2585',
                failedServers: '415',
                underMainServers: '315',
            },
        },
        {
            bgColor: 'color-bg-Yellow',
            text: 'North East',
            icon: 'perm_data_setting',
            title: 'US West (Oregon)',
            region: 'us-west-2',
            location : 'Oregon',
            zones: '6',
            launched :'2006',
            usage: '20',
            content: {
                title: 'US West (Oregon)',
                text: 'Physical location around the world where we cluster data centers. We call each group of logical data centers an Availability Zone',
                activeServers: '2585',
                failedServers: '415',
                underMainServers: '315',
            },
        },
        {
            bgColor: 'color-bg-Green',
            text: 'North East',
            icon: 'perm_data_setting',
            title: 'Africa (Cape Town)',
            region: 'af-south-1',
            location : 'Cape Town',
            zones: '0',
            launched :'2006',
            usage: '10',
            content: {
                title: 'Africa (Cape Town)',
                text: 'Physical location around the world where we cluster data centers. We call each group of logical data centers an Availability Zone',
                activeServers: '2585',
                failedServers: '415',
                underMainServers: '315',
            },
        },
        {
            bgColor: 'color-bg-Grey',
            text: 'North East',
            icon: 'perm_data_setting',
            title: 'Asia Pacific (Hong Kong)',
            region: 'ap-east-1',
            location : 'Hong Kong',
            zones: '6',
            launched :'2006',
            usage: '25',
            content: {
                title: 'Asia Pacific (Hong Kong)',
                text: 'Physical location around the world where we cluster data centers. We call each group of logical data centers an Availability Zone',
                activeServers: '2585',
                failedServers: '415',
                underMainServers: '315',
            },
        },
        {
            bgColor: 'color-bg-Cyan',
            text: 'North East',
            icon: 'perm_data_setting',
            title: 'Asia Pacific (Mumbai)',
            region: 'ap-south-1',
            location : 'Mumbai',
            zones: '6',
            launched :'2006',
            usage: '15',
            content: {
                title: 'Asia Pacific (Mumbai)',
                text: 'Physical location around the world where we cluster data centers. We call each group of logical data centers an Availability Zone',
                activeServers: '2585',
                failedServers: '415',
                underMainServers: '315',
            },
        },
        {
            bgColor: 'color-bg-Brown',
            text: 'North East',
            icon: 'perm_data_setting',
            title: 'Asia Pacific (Osaka)',
            region: 'ap-northeast-3',
            location : 'Osaka',
            zones: '6',
            launched :'2006',
            usage: '26',
            content: {
                title: 'Asia Pacific (Osaka)',
                text: 'Physical location around the world where we cluster data centers. We call each group of logical data centers an Availability Zone',
                activeServers: '2585',
                failedServers: '415',
                underMainServers: '315',
            },
        },
        {
            bgColor: 'color-bg-Cyan',
            text: 'North East',
            icon: 'perm_data_setting',
            title: 'Asia Pacific (Seoul)',
            region: 'ap-northeast-2',
            location : 'Seoul',
            zones: '6',
            launched :'2006',
            usage: '35',
            content: {
                title: 'Asia Pacific (Seoul)',
                text: 'Physical location around the world where we cluster data centers. We call each group of logical data centers an Availability Zone',
                activeServers: '2585',
                failedServers: '415',
                underMainServers: '315',
            },
        },
        {
            bgColor: 'color-bg-Black',
            text: 'North East',
            icon: 'perm_data_setting',
            title: 'Asia Pacific (Singapore)',
            region: 'ap-southeast-1',
            location : 'Singapore',
            zones: '6',
            launched :'2006',
            usage: '55',
            content: {
                title: 'Asia Pacific (Singapore)',
                text: 'Physical location around the world where we cluster data centers. We call each group of logical data centers an Availability Zone',
                activeServers: '2585',
                failedServers: '415',
                underMainServers: '315',
            },
        },
        {
            bgColor: 'color-bg-Orange',
            text: 'North East',
            icon: 'perm_data_setting',
            title: 'Asia Pacific (Sydney)',
            region: 'ap-southeast-2',
            location : 'Sydney',
            zones: '6',
            launched :'2006',
            usage: '52',
            content: {
                title: 'Asia Pacific (Sydney)',
                text: 'Physical location around the world where we cluster data centers. We call each group of logical data centers an Availability Zone',
                activeServers: '2585',
                failedServers: '415',
                underMainServers: '315',
            },
        },
        {
            bgColor: 'color-bg-Light-green',
            text: 'North East',
            icon: 'perm_data_setting',
            title: 'Asia Pacific (Tokyo)',
            region: 'ap-northeast-1',
            location : 'Tokyo',
            zones: '6',
            launched :'2006',
            usage: '65',
            content: {
                title: 'Asia Pacific (Tokyo)',
                text: 'Physical location around the world where we cluster data centers. We call each group of logical data centers an Availability Zone',
                activeServers: '2585',
                failedServers: '415',
                underMainServers: '315',
            },
        }
    ]
}